export const ITEM_LIST_REQUEST = 'ITEM_LIST_REQUEST'
export const ITEM_LIST_SUCCESS = 'ITEM_LIST_SUCCESS'
export const ITEM_LIST_FAIL = 'ITEM_LIST_FAIL'

export const ITEM_SOLO_REQUEST = 'ITEM_SOLO_REQUEST'
export const ITEM_SOLO_SUCCESS = 'ITEM_SOLO_SUCCESS'
export const ITEM_SOLO_FAIL = 'ITEM_SOLO_FAIL'

export const ITEM_CREATE_REQUEST = 'ITEM_CREATE_REQUEST'
export const ITEM_CREATE_SUCCESS = 'ITEM_CREATE_SUCCESS'
export const ITEM_CREATE_FAIL = 'ITEM_CREATE_FAIL'
